[tool.taskipy.tasks]
run = { cmd ="python src/main.py", help = "Runs the script." }
test = { cmd ="python -m pytest -v", help = "Runs all unit tests." }
test-ipdb = { cmd ="python -m pytest -v -s", help = "Runs all unit tests with ipdb." }
